name: Run Tests

on:
  workflow_dispatch:
  
jobs:
  build-linux:
    name: Build roboRIO Java/C++ and linux desktop
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2022-18.04
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Compile and run tests
        run: ./gradlew build
        
      - name: Publish
        run: ./gradlew publish
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: roborio-linux
          path: 'build/repos/releases/com/pathplanner/lib'
